### ISSUE TITLE
Support for esp8266

### ISSUE THREAD

**Issue by kroon040** [rene-d/oregon#2]
Hi,

I'm looking for someting like this , but then the  rxb6 connected to an esp8266, and mqtt support.

Is this possible that can be done?

regards RIchard

**Comment by rene-d** [comment]
Hi Richards,

Thanks for your interest :)

Unfortunately, I don't have an esp8266 module. So, I don't know if it is possible (but I guess yes). The rxb6 module works with voltage from 3 to 5V, compatible with the 3.3V Vcc of the esp8266.

**Comment by rene-d** [comment]
esp8266 support not planned.
